
###

GET http://localhost:9402/account/api/accounts/HC-2025-000015?effectiveDate=2025-04-01


###

GET http://localhost:9402/account/api/accounts/invalid-account-no?effectiveDate=2025-04-01


###

GET http://localhost:9402/account/actuator/metrics
###

GET http://localhost:9402/account/actuator/metrics/account.balance.not_found

###

GET http://localhost:9402/account/actuator/metrics/http.server.requests

###

GET http://localhost:9402/account/actuator/info



